import React from 'react'
import classes from './ItemsListV1.module.css'
const ItemsListV1 = () => {
  return (
    <div className={classes.main}>
        <div className={classes.filterBar}>Self-help books are great for gaining informing, self-education, and improving one's skills. There are a variety of such books available on e-commerce websites. Depending on what you are looking for, you can find the best self-help books that meet your needs. These books are available in various languages, such as English, Hindi, and Tamil. You can also find translations of the same book in several different languages. Of the various books that are available online, some popular ones are Achieve More, Succeed Faster (Hindi, Published by Manjul Publishing House, Author Deepak Bajaj), which talks about the 31 gains of direct selling; Chanakya in Daily Life (English, Published by Rupa & Co., Author Radhakrishnan Pillai), which is about using the principles of Chanakya in daily life for more impact; and Flowers on the Path (English, Published by Penguin Random House India, Author Sadhguru), which covers topics like challenges faced by individuals, worldly affairs, social issues, and dimensions of the beyond. You can also check out Power of Your Subconscious Mind (Tamil, Published by Manjul, Author Dr. Joseph Murphy), which is a book that guides readers to achieve the impossible every day of their lives. You can browse through these books available online. To get these self-help books delivered to your doorstep, you can place your order now. This information is updated on 25-Jan-23</div>
        <div  className={classes.mainBar}>Self-help books are great for gaining informing, self-education, and improving one's skills. There are a variety of such books available on e-commerce websites. Depending on what you are looking for, you can find the best self-help books that meet your needs. These books are available in various languages, such as English, Hindi, and Tamil. You can also find translations of the same book in several different languages. Of the various books that are available online, some popular ones are Achieve More, Succeed Faster (Hindi, Published by Manjul Publishing House, Author Deepak Bajaj), which talks about the 31 gains of direct selling; Chanakya in Daily Life (English, Published by Rupa & Co., Author Radhakrishnan Pillai), which is about using the principles of Chanakya in daily life for more impact; and Flowers on the Path (English, Published by Penguin Random House India, Author Sadhguru), which covers topics like challenges faced by individuals, worldly affairs, social issues, and dimensions of the beyond. You can also check out Power of Your Subconscious Mind (Tamil, Published by Manjul, Author Dr. Joseph Murphy), which is a book that guides readers to achieve the impossible every day of their lives. You can browse through these books available online. To get these self-help books delivered to your doorstep, you can place your order now. This information is updated on 25-Jan-23</div>
    </div>
  )
}

export default ItemsListV1